### ISSUE TITLE
Final test with qr code generator doesnt work

### ISSUE THREAD

**Issue by mraeclo** [mir-lab/touchdesigner-summit-2019-external-python#15]
Hello, thanks a lot for the tutorials!

I followed the tutorials and everything seemed to be working until the end. All prints printed the correct directories but when I run the script "text_qrmaker" inside TD to create the qr code based on the table DAT It doesnt generate the qr code and TD give me this errors, which have my machine directory for python libraries.

`Traceback (most recent call last):
  File "</base_qrcode/text_qrmaker:op('/base_qrcode/text_qrmaker').run()>", line 1
td.Error: File "/base_qrcode/text_qrmaker", line 7
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/qrcode/main.py", line 11, in make
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/qrcode/main.py", line 289, in make_image
    r = previousimport(*args, **kw)
ModuleNotFoundError: No module named 'qrcode.image.pil'
Results of run operation resulted in exception. Value:type:textDAT path:/base_qrcode/text_qrmaker Type:<class 'td.textDAT'>.`

I rechecked other scripts and if the files are on the correct folders and everything seems to be correct. Any thoughts?

Touch designer 64-bit build 2019.33020
Macbook pro OSX 10.13.6

Thanks in advance
Marcelo

**Comment by raganmd** [comment]
Hi @Mraeclo looking at this the error message it seems like you're missing a library. What are the libraries that you used for your requirements.txt?

**Comment by mraeclo** [comment]
thanks for the answer @raganmd . I was testing with only the qr code library like you did on the tutorial before trying with the libraries I want to use, so inside the requierements there is only

`qrcode[pil]`

I wonder if this has something to do with the "Python 64 bit module path" on TD preferences, what folder should that be? My current folder is  /Library/Frameworks/Python.framework/Versions/3.5

**Comment by raganmd** [comment]
did you also install the python stand alone on your machine? There's also a different set of instructions for the approach on Mac vs windows. Sorry for all the questions, getting this to behave as expected is often tricky the first time around.

**Comment by raganmd** [comment]
@Mraeclo you might also check your dep folder in your project folder to confirm that you've actually pulled the external library. 

The other trouble shooting step here would be to step through the helper process that adds your `dep` folder to TD's sys.path, then try a direct import in the text port. That will help you track down where the issues are coming from.

**Comment by mraeclo** [comment]
1. If installing the python standalone means having the Python 3.5 folder on the Applications folder then yes. Is it supposed to be there?

2. Inside dep/Python there are the folders of the library 

3. Ill try the trouble shooting step you said.

Thanks again!

**Comment by raganmd** [comment]
@Mraeclo any luck?

**Comment by HarshiniJK** [comment]
I'm having the exact same problem. Was it ever resolved?

**Comment by raganmd** [comment]
@HarshiniJK - what platform and TouchDesigner build are you using?

**Comment by HarshiniJK** [comment]
Hey Matthew! I managed to get it working with a tox from alphamoonbase. Not
sure why it worked - something about the directories, but I tried the
newest touchdesigner and on a separate machine tried the same versions you
were using. Still had a problem at that final step.
